# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_murocontencion.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1145, 744)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setSpacing(1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_5.sizePolicy().hasHeightForWidth())
        self.scrollArea_5.setSizePolicy(sizePolicy)
        self.scrollArea_5.setMinimumSize(QtCore.QSize(0, 100))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 163, 145))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_11.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_11.setSpacing(2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.gridLayout_11.addWidget(self.label_44, 2, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.gridLayout_11.addWidget(self.label_48, 4, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.gridLayout_11.addWidget(self.label_45, 3, 0, 1, 1)
        self.fsPPSCVout = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.fsPPSCVout.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.fsPPSCVout.setFont(font)
        self.fsPPSCVout.setMaxLength(4)
        self.fsPPSCVout.setReadOnly(True)
        self.fsPPSCVout.setObjectName("fsPPSCVout")
        self.gridLayout_11.addWidget(self.fsPPSCVout, 3, 1, 1, 1)
        self.fsPPSCDout = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.fsPPSCDout.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.fsPPSCDout.setFont(font)
        self.fsPPSCDout.setMaxLength(4)
        self.fsPPSCDout.setReadOnly(True)
        self.fsPPSCDout.setObjectName("fsPPSCDout")
        self.gridLayout_11.addWidget(self.fsPPSCDout, 2, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.gridLayout_11.addWidget(self.label_43, 0, 0, 1, 2)
        self.label_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_11.addWidget(self.label_47, 1, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_11.addWidget(self.label_49, 5, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_11.addWidget(self.label_50, 6, 0, 1, 1)
        self.fsPPSISDout = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.fsPPSISDout.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.fsPPSISDout.setFont(font)
        self.fsPPSISDout.setMaxLength(4)
        self.fsPPSISDout.setObjectName("fsPPSISDout")
        self.gridLayout_11.addWidget(self.fsPPSISDout, 5, 1, 1, 1)
        self.fsPPSISVout = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.fsPPSISVout.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.fsPPSISVout.setFont(font)
        self.fsPPSISVout.setMaxLength(4)
        self.fsPPSISVout.setObjectName("fsPPSISVout")
        self.gridLayout_11.addWidget(self.fsPPSISVout, 6, 1, 1, 1)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_10.addWidget(self.scrollArea_5, 2, 4, 1, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 274, 230))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.teView = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_3)
        self.teView.setObjectName("teView")
        self.gridLayout_2.addWidget(self.teView, 1, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_10.addWidget(self.scrollArea_3, 2, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(256, 350))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 254, 348))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Symbol")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 2, 1, 1)
        self.dInput = QtWidgets.QDoubleSpinBox(self.frame)
        self.dInput.setMaximumSize(QtCore.QSize(50, 16777215))
        self.dInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dInput.setAlignment(QtCore.Qt.AlignCenter)
        self.dInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dInput.setMaximum(4.0)
        self.dInput.setSingleStep(0.05)
        self.dInput.setProperty("value", 2.0)
        self.dInput.setObjectName("dInput")
        self.gridLayout_3.addWidget(self.dInput, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 2, 1, 1)
        self.khInput = QtWidgets.QDoubleSpinBox(self.frame)
        self.khInput.setMaximumSize(QtCore.QSize(50, 16777215))
        self.khInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.khInput.setAlignment(QtCore.Qt.AlignCenter)
        self.khInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.khInput.setMaximum(0.5)
        self.khInput.setSingleStep(0.05)
        self.khInput.setProperty("value", 0.15)
        self.khInput.setObjectName("khInput")
        self.gridLayout_3.addWidget(self.khInput, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.kvInput = QtWidgets.QDoubleSpinBox(self.frame)
        self.kvInput.setMaximumSize(QtCore.QSize(50, 16777215))
        self.kvInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.kvInput.setAlignment(QtCore.Qt.AlignCenter)
        self.kvInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.kvInput.setMaximum(0.3)
        self.kvInput.setSingleStep(0.05)
        self.kvInput.setProperty("value", 0.08)
        self.kvInput.setObjectName("kvInput")
        self.gridLayout_3.addWidget(self.kvInput, 3, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Symbol")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 4, 2, 1, 1)
        self.phiInput = QtWidgets.QDoubleSpinBox(self.frame)
        self.phiInput.setMaximumSize(QtCore.QSize(50, 16777215))
        self.phiInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.phiInput.setAlignment(QtCore.Qt.AlignCenter)
        self.phiInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.phiInput.setDecimals(0)
        self.phiInput.setMaximum(90.0)
        self.phiInput.setSingleStep(1.0)
        self.phiInput.setProperty("value", 30.0)
        self.phiInput.setObjectName("phiInput")
        self.gridLayout_3.addWidget(self.phiInput, 4, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Symbol")
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 5, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 6, 2, 1, 1)
        self.qscInput = QtWidgets.QDoubleSpinBox(self.frame)
        self.qscInput.setMaximumSize(QtCore.QSize(50, 16777215))
        self.qscInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.qscInput.setAlignment(QtCore.Qt.AlignCenter)
        self.qscInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.qscInput.setMaximum(5.0)
        self.qscInput.setSingleStep(0.05)
        self.qscInput.setProperty("value", 0.5)
        self.qscInput.setObjectName("qscInput")
        self.gridLayout_3.addWidget(self.qscInput, 6, 3, 1, 1)
        self.muInput = QtWidgets.QDoubleSpinBox(self.frame)
        self.muInput.setMaximumSize(QtCore.QSize(50, 16777215))
        self.muInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.muInput.setAlignment(QtCore.Qt.AlignCenter)
        self.muInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.muInput.setMaximum(1.0)
        self.muInput.setSingleStep(0.05)
        self.muInput.setProperty("value", 0.2)
        self.muInput.setObjectName("muInput")
        self.gridLayout_3.addWidget(self.muInput, 5, 3, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.frame)
        self.label_56.setObjectName("label_56")
        self.gridLayout_3.addWidget(self.label_56, 8, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.frame)
        self.label_57.setObjectName("label_57")
        self.gridLayout_3.addWidget(self.label_57, 8, 2, 1, 1)
        self.kaeOut = QtWidgets.QLineEdit(self.frame)
        self.kaeOut.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.kaeOut.setFont(font)
        self.kaeOut.setMaxLength(4)
        self.kaeOut.setAlignment(QtCore.Qt.AlignCenter)
        self.kaeOut.setReadOnly(True)
        self.kaeOut.setObjectName("kaeOut")
        self.gridLayout_3.addWidget(self.kaeOut, 8, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 7, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 7, 2, 1, 1)
        self.kaInput = QtWidgets.QDoubleSpinBox(self.frame)
        self.kaInput.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.kaInput.setFont(font)
        self.kaInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.kaInput.setAlignment(QtCore.Qt.AlignCenter)
        self.kaInput.setReadOnly(False)
        self.kaInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.kaInput.setMaximum(1.0)
        self.kaInput.setSingleStep(0.05)
        self.kaInput.setProperty("value", 0.3)
        self.kaInput.setObjectName("kaInput")
        self.gridLayout_3.addWidget(self.kaInput, 7, 3, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.frame)
        self.label_60.setObjectName("label_60")
        self.gridLayout_3.addWidget(self.label_60, 9, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.frame)
        self.label_62.setObjectName("label_62")
        self.gridLayout_3.addWidget(self.label_62, 9, 2, 1, 1)
        self.kpOut = QtWidgets.QDoubleSpinBox(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.kpOut.setFont(font)
        self.kpOut.setAlignment(QtCore.Qt.AlignCenter)
        self.kpOut.setReadOnly(True)
        self.kpOut.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.kpOut.setObjectName("kpOut")
        self.gridLayout_3.addWidget(self.kpOut, 9, 3, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_8.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_8.addWidget(self.label_26, 0, 1, 1, 1)
        self.eInput = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.eInput.setMaximumSize(QtCore.QSize(50, 16777215))
        self.eInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.eInput.setAlignment(QtCore.Qt.AlignCenter)
        self.eInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.eInput.setMinimum(0.1)
        self.eInput.setMaximum(0.6)
        self.eInput.setSingleStep(0.05)
        self.eInput.setProperty("value", 0.2)
        self.eInput.setObjectName("eInput")
        self.gridLayout_8.addWidget(self.eInput, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_8.addWidget(self.label_27, 1, 1, 1, 1)
        self.hmInput = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.hmInput.setMaximumSize(QtCore.QSize(50, 16777215))
        self.hmInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.hmInput.setAlignment(QtCore.Qt.AlignCenter)
        self.hmInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.hmInput.setMaximum(10.0)
        self.hmInput.setSingleStep(0.05)
        self.hmInput.setProperty("value", 2.0)
        self.hmInput.setObjectName("hmInput")
        self.gridLayout_8.addWidget(self.hmInput, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 2, 1, 1, 1)
        self.hfInput = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.hfInput.setMaximumSize(QtCore.QSize(50, 16777215))
        self.hfInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.hfInput.setAlignment(QtCore.Qt.AlignCenter)
        self.hfInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.hfInput.setMaximum(5.0)
        self.hfInput.setSingleStep(0.05)
        self.hfInput.setProperty("value", 0.2)
        self.hfInput.setObjectName("hfInput")
        self.gridLayout_8.addWidget(self.hfInput, 2, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 3, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 3, 1, 1, 1)
        self.hdInput = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.hdInput.setMaximumSize(QtCore.QSize(50, 16777215))
        self.hdInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.hdInput.setAlignment(QtCore.Qt.AlignCenter)
        self.hdInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.hdInput.setMaximum(2.0)
        self.hdInput.setSingleStep(0.05)
        self.hdInput.setProperty("value", 0.0)
        self.hdInput.setObjectName("hdInput")
        self.gridLayout_8.addWidget(self.hdInput, 3, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_8.addWidget(self.label_23, 4, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 4, 1, 1, 1)
        self.l1Input = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.l1Input.setMaximumSize(QtCore.QSize(50, 16777215))
        self.l1Input.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.l1Input.setAlignment(QtCore.Qt.AlignCenter)
        self.l1Input.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.l1Input.setMaximum(5.0)
        self.l1Input.setSingleStep(0.05)
        self.l1Input.setProperty("value", 0.2)
        self.l1Input.setObjectName("l1Input")
        self.gridLayout_8.addWidget(self.l1Input, 4, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_8.addWidget(self.label_24, 5, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frame_2)
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 5, 1, 1, 1)
        self.l2Input = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.l2Input.setMaximumSize(QtCore.QSize(50, 16777215))
        self.l2Input.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.l2Input.setAlignment(QtCore.Qt.AlignCenter)
        self.l2Input.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.l2Input.setMaximum(20.0)
        self.l2Input.setSingleStep(0.05)
        self.l2Input.setProperty("value", 1.0)
        self.l2Input.setObjectName("l2Input")
        self.gridLayout_8.addWidget(self.l2Input, 5, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Symbol")
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_8.addWidget(self.label_32, 6, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_2)
        self.label_33.setObjectName("label_33")
        self.gridLayout_8.addWidget(self.label_33, 6, 1, 1, 1)
        self.betaInput = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.betaInput.setMaximumSize(QtCore.QSize(50, 16777215))
        self.betaInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.betaInput.setAlignment(QtCore.Qt.AlignCenter)
        self.betaInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.betaInput.setObjectName("betaInput")
        self.gridLayout_8.addWidget(self.betaInput, 6, 2, 1, 1)
        self.gridLayout_6.addWidget(self.frame_2, 1, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_10.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_58 = QtWidgets.QLabel(self.frame_3)
        self.label_58.setObjectName("label_58")
        self.gridLayout_4.addWidget(self.label_58, 8, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.frame_3)
        self.label_61.setObjectName("label_61")
        self.gridLayout_4.addWidget(self.label_61, 10, 0, 1, 1)
        self.cOut = QtWidgets.QLineEdit(self.frame_3)
        self.cOut.setMaxLength(4)
        self.cOut.setAlignment(QtCore.Qt.AlignCenter)
        self.cOut.setObjectName("cOut")
        self.gridLayout_4.addWidget(self.cOut, 8, 1, 1, 1)
        self.wMuroOut = QtWidgets.QLineEdit(self.frame_3)
        self.wMuroOut.setMaxLength(4)
        self.wMuroOut.setAlignment(QtCore.Qt.AlignCenter)
        self.wMuroOut.setReadOnly(True)
        self.wMuroOut.setObjectName("wMuroOut")
        self.gridLayout_4.addWidget(self.wMuroOut, 0, 1, 1, 1)
        self.eActivoOut = QtWidgets.QLineEdit(self.frame_3)
        self.eActivoOut.setMaxLength(4)
        self.eActivoOut.setAlignment(QtCore.Qt.AlignCenter)
        self.eActivoOut.setReadOnly(True)
        self.eActivoOut.setObjectName("eActivoOut")
        self.gridLayout_4.addWidget(self.eActivoOut, 3, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.frame_3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 0, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.frame_3)
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 1, 0, 1, 1)
        self.wTierraOut = QtWidgets.QLineEdit(self.frame_3)
        self.wTierraOut.setMaxLength(4)
        self.wTierraOut.setAlignment(QtCore.Qt.AlignCenter)
        self.wTierraOut.setReadOnly(True)
        self.wTierraOut.setObjectName("wTierraOut")
        self.gridLayout_4.addWidget(self.wTierraOut, 1, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.frame_3)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 2, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.frame_3)
        self.label_39.setObjectName("label_39")
        self.gridLayout_4.addWidget(self.label_39, 3, 0, 1, 1)
        self.eSismoOut = QtWidgets.QLineEdit(self.frame_3)
        self.eSismoOut.setMaxLength(4)
        self.eSismoOut.setAlignment(QtCore.Qt.AlignCenter)
        self.eSismoOut.setReadOnly(True)
        self.eSismoOut.setObjectName("eSismoOut")
        self.gridLayout_4.addWidget(self.eSismoOut, 4, 1, 1, 1)
        self.mResistenteOut = QtWidgets.QLineEdit(self.frame_3)
        self.mResistenteOut.setMaxLength(4)
        self.mResistenteOut.setAlignment(QtCore.Qt.AlignCenter)
        self.mResistenteOut.setReadOnly(True)
        self.mResistenteOut.setObjectName("mResistenteOut")
        self.gridLayout_4.addWidget(self.mResistenteOut, 2, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.frame_3)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 4, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.frame_3)
        self.label_41.setObjectName("label_41")
        self.gridLayout_4.addWidget(self.label_41, 7, 0, 1, 1)
        self.roceOut = QtWidgets.QLineEdit(self.frame_3)
        self.roceOut.setMaxLength(4)
        self.roceOut.setAlignment(QtCore.Qt.AlignCenter)
        self.roceOut.setReadOnly(True)
        self.roceOut.setObjectName("roceOut")
        self.gridLayout_4.addWidget(self.roceOut, 7, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.frame_3)
        self.label_42.setObjectName("label_42")
        self.gridLayout_4.addWidget(self.label_42, 9, 0, 1, 1)
        self.ePasivoEOut = QtWidgets.QLineEdit(self.frame_3)
        self.ePasivoEOut.setMaxLength(4)
        self.ePasivoEOut.setAlignment(QtCore.Qt.AlignCenter)
        self.ePasivoEOut.setReadOnly(True)
        self.ePasivoEOut.setObjectName("ePasivoEOut")
        self.gridLayout_4.addWidget(self.ePasivoEOut, 9, 1, 1, 1)
        self.eScOut = QtWidgets.QLineEdit(self.frame_3)
        self.eScOut.setMaxLength(4)
        self.eScOut.setAlignment(QtCore.Qt.AlignCenter)
        self.eScOut.setObjectName("eScOut")
        self.gridLayout_4.addWidget(self.eScOut, 5, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.frame_3)
        self.label_46.setObjectName("label_46")
        self.gridLayout_4.addWidget(self.label_46, 5, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_3)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 6, 0, 1, 1)
        self.mVocanteOut = QtWidgets.QLineEdit(self.frame_3)
        self.mVocanteOut.setMaxLength(4)
        self.mVocanteOut.setAlignment(QtCore.Qt.AlignCenter)
        self.mVocanteOut.setObjectName("mVocanteOut")
        self.gridLayout_4.addWidget(self.mVocanteOut, 6, 1, 1, 1)
        self.ePasivoSOut = QtWidgets.QLineEdit(self.frame_3)
        self.ePasivoSOut.setMaxLength(4)
        self.ePasivoSOut.setAlignment(QtCore.Qt.AlignCenter)
        self.ePasivoSOut.setObjectName("ePasivoSOut")
        self.gridLayout_4.addWidget(self.ePasivoSOut, 10, 1, 1, 1)
        self.label_35.raise_()
        self.wMuroOut.raise_()
        self.label_36.raise_()
        self.wTierraOut.raise_()
        self.label_38.raise_()
        self.mResistenteOut.raise_()
        self.label_39.raise_()
        self.eActivoOut.raise_()
        self.label_40.raise_()
        self.eSismoOut.raise_()
        self.label_41.raise_()
        self.roceOut.raise_()
        self.label_42.raise_()
        self.ePasivoEOut.raise_()
        self.eScOut.raise_()
        self.label_46.raise_()
        self.label_37.raise_()
        self.mVocanteOut.raise_()
        self.cOut.raise_()
        self.label_58.raise_()
        self.label_61.raise_()
        self.ePasivoSOut.raise_()
        self.gridLayout_10.addWidget(self.frame_3, 2, 2, 1, 1)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_4.sizePolicy().hasHeightForWidth())
        self.scrollArea_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.scrollArea_4.setFont(font)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 274, 230))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.tsView = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_4)
        self.tsView.setObjectName("tsView")
        self.gridLayout_5.addWidget(self.tsView, 1, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_10.addWidget(self.scrollArea_4, 2, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(9, 2, 1, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_63 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_63.setFont(font)
        self.label_63.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_63.setObjectName("label_63")
        self.verticalLayout.addWidget(self.label_63)
        self.gridLayout_10.addWidget(self.widget, 3, 4, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_10.addWidget(self.label_34, 1, 0, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 350))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 848, 348))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.muroView = MuroView(self.scrollAreaWidgetContents_2)
        self.muroView.setRenderHints(QtGui.QPainter.TextAntialiasing)
        self.muroView.setViewportUpdateMode(QtWidgets.QGraphicsView.BoundingRectViewportUpdate)
        self.muroView.setObjectName("muroView")
        self.gridLayout.addWidget(self.muroView, 1, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_10.addWidget(self.scrollArea_2, 0, 1, 1, 4)
        self.scrollArea_6 = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_6.sizePolicy().hasHeightForWidth())
        self.scrollArea_6.setSizePolicy(sizePolicy)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 141, 142))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_54.setObjectName("label_54")
        self.gridLayout_7.addWidget(self.label_54, 0, 0, 1, 1)
        self.fyInput = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_6)
        self.fyInput.setMaximumSize(QtCore.QSize(35, 16777215))
        self.fyInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.fyInput.setAlignment(QtCore.Qt.AlignCenter)
        self.fyInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.fyInput.setDecimals(0)
        self.fyInput.setMinimum(240.0)
        self.fyInput.setMaximum(420.0)
        self.fyInput.setSingleStep(1000.0)
        self.fyInput.setProperty("value", 420.0)
        self.fyInput.setObjectName("fyInput")
        self.gridLayout_7.addWidget(self.fyInput, 0, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_53.setObjectName("label_53")
        self.gridLayout_7.addWidget(self.label_53, 1, 0, 1, 1)
        self.fcInput = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_6)
        self.fcInput.setMaximumSize(QtCore.QSize(35, 16777215))
        self.fcInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.fcInput.setAlignment(QtCore.Qt.AlignCenter)
        self.fcInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.fcInput.setDecimals(0)
        self.fcInput.setMinimum(16.0)
        self.fcInput.setMaximum(35.0)
        self.fcInput.setSingleStep(5.0)
        self.fcInput.setProperty("value", 16.0)
        self.fcInput.setObjectName("fcInput")
        self.gridLayout_7.addWidget(self.fcInput, 1, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_52.setObjectName("label_52")
        self.gridLayout_7.addWidget(self.label_52, 2, 0, 1, 1)
        self.recInput = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_6)
        self.recInput.setMaximumSize(QtCore.QSize(35, 16777215))
        self.recInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.recInput.setAlignment(QtCore.Qt.AlignCenter)
        self.recInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.recInput.setDecimals(1)
        self.recInput.setMinimum(1.0)
        self.recInput.setMaximum(7.0)
        self.recInput.setSingleStep(0.05)
        self.recInput.setProperty("value", 2.5)
        self.recInput.setObjectName("recInput")
        self.gridLayout_7.addWidget(self.recInput, 2, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.gridLayout_7.addWidget(self.label_55, 3, 0, 1, 2)
        self.muOut = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.muOut.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.muOut.setFont(font)
        self.muOut.setMaxLength(4)
        self.muOut.setObjectName("muOut")
        self.gridLayout_7.addWidget(self.muOut, 3, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_7.addWidget(self.label_51, 4, 0, 1, 2)
        self.asOut = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.asOut.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.asOut.setFont(font)
        self.asOut.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.asOut.setMaxLength(4)
        self.asOut.setAlignment(QtCore.Qt.AlignCenter)
        self.asOut.setObjectName("asOut")
        self.gridLayout_7.addWidget(self.asOut, 4, 2, 1, 1)
        self.label_52.raise_()
        self.recInput.raise_()
        self.label_53.raise_()
        self.fcInput.raise_()
        self.label_54.raise_()
        self.fyInput.raise_()
        self.label_55.raise_()
        self.muOut.raise_()
        self.label_51.raise_()
        self.asOut.raise_()
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout_10.addWidget(self.scrollArea_6, 2, 3, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1145, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionCalcular = QtWidgets.QAction(MainWindow)
        self.actionCalcular.setObjectName("actionCalcular")
        self.toolBar.addAction(self.actionCalcular)
        self.label_44.setBuddy(self.wMuroOut)
        self.label_45.setBuddy(self.wMuroOut)
        self.label_35.setBuddy(self.wMuroOut)
        self.label_36.setBuddy(self.wTierraOut)
        self.label_38.setBuddy(self.mResistenteOut)
        self.label_39.setBuddy(self.eActivoOut)
        self.label_40.setBuddy(self.eSismoOut)
        self.label_41.setBuddy(self.roceOut)
        self.label_42.setBuddy(self.ePasivoEOut)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cálculo de Muro de Contención en Cantilever"))
        self.label_44.setText(_translate("MainWindow", "FS deslizamiento :"))
        self.label_48.setText(_translate("MainWindow", "PP + SISMO"))
        self.label_45.setText(_translate("MainWindow", "FS volcamiento :"))
        self.label_43.setText(_translate("MainWindow", "Factores de Seguridad:"))
        self.label_47.setText(_translate("MainWindow", "PP + SC"))
        self.label_49.setText(_translate("MainWindow", "FS deslizamiento:"))
        self.label_50.setText(_translate("MainWindow", "FS volcamiento:"))
        self.label_3.setText(_translate("MainWindow", "Tensiones Estáticas [ton/m2]:"))
        self.label.setText(_translate("MainWindow", "Parámetros:"))
        self.label_25.setText(_translate("MainWindow", "Dimensiones:"))
        self.label_18.setText(_translate("MainWindow", "[adim]:"))
        self.label_5.setText(_translate("MainWindow", "g"))
        self.label_12.setText(_translate("MainWindow", "[ton/m3]:"))
        self.label_7.setText(_translate("MainWindow", "Kh"))
        self.label_14.setText(_translate("MainWindow", "[adim]:"))
        self.label_8.setText(_translate("MainWindow", "Kv"))
        self.label_9.setText(_translate("MainWindow", "f"))
        self.label_16.setText(_translate("MainWindow", "[º]:"))
        self.label_10.setText(_translate("MainWindow", "m"))
        self.label_15.setText(_translate("MainWindow", "[adim]:"))
        self.label_11.setText(_translate("MainWindow", "qsc"))
        self.label_17.setText(_translate("MainWindow", "[ton/m2]:"))
        self.label_56.setText(_translate("MainWindow", "Kae"))
        self.label_57.setText(_translate("MainWindow", "[adim]:"))
        self.label_6.setText(_translate("MainWindow", "Ka"))
        self.label_13.setText(_translate("MainWindow", "[adim]:"))
        self.label_60.setText(_translate("MainWindow", "kp"))
        self.label_62.setText(_translate("MainWindow", "[adim]:"))
        self.label_19.setText(_translate("MainWindow", "e"))
        self.label_26.setText(_translate("MainWindow", "[m]:"))
        self.label_20.setText(_translate("MainWindow", "Hm"))
        self.label_27.setText(_translate("MainWindow", "[m]:"))
        self.label_21.setText(_translate("MainWindow", "Hf"))
        self.label_28.setText(_translate("MainWindow", "[m]:"))
        self.label_22.setText(_translate("MainWindow", "Hd"))
        self.label_29.setText(_translate("MainWindow", "[m]:"))
        self.label_23.setText(_translate("MainWindow", "L1"))
        self.label_30.setText(_translate("MainWindow", "[m]:"))
        self.label_24.setText(_translate("MainWindow", "L2"))
        self.label_31.setText(_translate("MainWindow", "[m]:"))
        self.label_32.setText(_translate("MainWindow", "b"))
        self.label_33.setText(_translate("MainWindow", "[º]:"))
        self.label_58.setText(_translate("MainWindow", "c Pasivo  [cm]"))
        self.label_61.setText(_translate("MainWindow", "e Pasivo Sis. [ton]:"))
        self.label_35.setText(_translate("MainWindow", "w Muro [ton]:"))
        self.label_36.setText(_translate("MainWindow", "w Tierra [ton]:"))
        self.label_38.setText(_translate("MainWindow", "m Resistente [ton m]:"))
        self.label_39.setText(_translate("MainWindow", "e Activo [ton]:"))
        self.label_40.setText(_translate("MainWindow", "e Sismo [ton]:"))
        self.label_41.setText(_translate("MainWindow", "roce [ton]:"))
        self.label_42.setText(_translate("MainWindow", "e Pasivo Est. [ton]:"))
        self.label_46.setText(_translate("MainWindow", "e SC [ton]:"))
        self.label_37.setText(_translate("MainWindow", "m Volcante [ton m]:"))
        self.label_4.setText(_translate("MainWindow", "Tensiones Sísmicas [ton/m2]:"))
        self.label_63.setText(_translate("MainWindow", "Felipe Cordero Osorio"))
        self.label_34.setText(_translate("MainWindow", "Resultados:"))
        self.label_2.setText(_translate("MainWindow", "Dibujo del Muro:"))
        self.label_54.setText(_translate("MainWindow", "fy [MPa]:"))
        self.label_53.setText(_translate("MainWindow", "fc [MPa]:"))
        self.label_52.setText(_translate("MainWindow", "rec[cm]:"))
        self.label_55.setText(_translate("MainWindow", "Mu [ton m]:"))
        self.label_51.setText(_translate("MainWindow", "As [cm2/m]:"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionCalcular.setText(_translate("MainWindow", "Calcular"))
        self.actionCalcular.setToolTip(_translate("MainWindow", "actualizar cálculos"))
        self.actionCalcular.setShortcut(_translate("MainWindow", "F10"))
from dibujarmuro import MuroView
